name: vertical_calendar
description: A really simple calendar with a vertical scroll.
version: 1.0.1
homepage: https://github.com/g123k/flutter_vertical_calendar

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: