name: paged_vertical_calendar
description: A simple paginated framework for implementing calendar based interfaces.
homepage: https://github.com/casvanluijtelaar/paged_vertical_calendar.git
repository: https://github.com/casvanluijtelaar/paged_vertical_calendar.git
version: 1.0.0-nullsafety.0

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  infinite_scroll_pagination: ^3.0.0-nullsafety.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
