name: paged_vertical_calendar
description: A simple paginated framework for implementing calendar based interfaces.
homepage: https://github.com/casvanluijtelaar/paged_vertical_calendar.git
repository: https://github.com/casvanluijtelaar/paged_vertical_calendar.git
authors:
  - "casvanluijtelaar"
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  infinite_scroll_pagination: ^2.3.0
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
