name: vertical_calendar
description: A new flutter plugin project.
version: 1.0.0
author:
homepage: https://github.com/g123k/flutter_vertical_calendar

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: